### ISSUE TITLE
DenyHosts will not start up!  Comes back with Python UTF-8 error

### ISSUE THREAD

**Issue by cyberpower678** [denyhosts/denyhosts#114]
`# /usr/local/etc/rc.d/denyhosts start
Starting denyhosts.
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 229, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/deny_hosts.py", line 78, in __init__
    offset = self.process_log(logfile, last_offset)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/deny_hosts.py", line 425, in process_log
    for line in fp:
  File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 8180: invalid continuation byte

DenyHosts exited abnormally
`

Currently running FreeBSD

**Comment by josev814** [comment]
I'm loading up a FreeBSD image within Hyper-V to test out.  I did notice that line 425 was from the previous github commit for the code in question, and not the lates, but looking at the files I don't see what the issue would be.  I'll let you know what I find out with it.

**Comment by josev814** [comment]
I was unable to replicate your issue.  I did write some updates that will help with the python3 conversion script that will work within freebsd, since bash isn't installed by default.

The newest version is 3.1.2 that I just committed and merged that you can test out.

**Comment by cyberpower678** [comment]
I was able to get around by setting the encoding to ISO, but denyhosts doesn't do anything when it runs.  Maybe it's because I have a modified FreeBSD setup called XigmaNAS, but it won't action the logs.

**Comment by josev814** [comment]
What happens if you run denyhosts this way

```
`whereis daemon-control-dist | awk '{ print $2 }'` start
`whereis daemon-control-dist | awk '{ print $2 }'` status
`whereis daemon-control-dist | awk '{ print $2 }'` stop
```

**Comment by josev814** [comment]
I attempted to install XigmaNAS 12 in Hyper-V.  It installed, but I wasn't able to login via shell with the default creds that they said it should be.  I also saw some errors and wasn't getting an ip assigned to the VM.  My FreeBSD version gets an ip without any issues.  I'm going to try v11 to see if I can get any further with that version.

**Comment by kozarenko** [comment]
Hello, Jose.
Fragment in attached file cause error 
'utf-8' codec can't decode byte 0xd1 in position 702: invalid continuation byte
[auth.log.gz](https://github.com/denyhosts/denyhosts/files/4465722/auth.log.gz)

**Comment by kozarenko** [comment]
Hello, Jose.
Fragment in attached file cause error 
'utf-8' codec can't decode byte 0xd1 in position 702: invalid continuation byte

FreeBSD 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64

[auth.log.gz](https://github.com/denyhosts/denyhosts/files/4465722/auth.log.gz)

**Comment by josev814** [comment]
@kozarenko it doesn't like the user here.
```Verify user 'ÑÑÐnedlindm'```
I'll have to see if there's a better way to check the user there.

**Comment by josev814** [comment]
What I'm seeing is that if I set deny_hosts.py to use the encoding of 'latin1' to open the file it parses correctly.  By default, FREEBSD is using utf-8 to open the file, and at line 425 when it goes to read the file it breaks, because of the non-utf8 characters.

I'm looking at how we can either support a fallback character set to go to latin1 as a backup if the default fails.  Otherwise, it may be something we need to include in the CONFIG file to allow a user to define what charset to use on their OS.

If anyone has any better thoughts on handling that, let me know.

**Comment by josev814** [comment]
@kozarenko I have a branch that I have tested to cover encoding fallback.  Would you mind testing it on your instance?

My repo is https://github.com/josev814/denyhosts.git and the branch is bug_114
