### ISSUE TITLE
ipaddr.py unsupported by python: now it's ipaddress.py (Python v3.x)

### ISSUE THREAD

**Issue by AdasOsorus** [denyhosts/denyhosts#118]
Try to install denyhost on Ubuntu on 20.04-LTS which is on Python 3.8
**Install fail at requirement : ipaddr.py** 

##################################
python setup.py install
  Traceback (most recent call last):
    File "setup.py", line 10, in <module>
      from DenyHosts.util import normalize_whitespace
    File "/tmp/denyhosts/DenyHosts/util.py", line 9, in <module>
      import ipaddr
  ModuleNotFoundError: No module named 'ipaddr'
##################################

As per (https://pypi.org/project/ipaddr/) seems that **ipaddr.py** has been superseded by **ipaddress.py**

Solution: ln -s /usr/lib/python3.8/ipaddress.py /usr/lib/python3.8/ipaddr.py
##################################
python setup.py install
  running install
  running build
  running build_py
  running build_scripts
  running install_lib
  running install_scripts
  changing mode of /usr/local/bin/daemon-control-dist to 755
  changing mode of /usr/local/bin/denyhosts.py to 755
  running install_data
  running install_egg_info
  Removing /usr/local/lib/python3.8/dist-packages/DenyHosts-3.0.egg-info
  Writing /usr/local/lib/python3.8/dist-packages/DenyHosts-3.0.egg-info
##################################

**Comment by josev814** [comment]
We have it set to detect the python version and then import the proper module depending on the python major version.  Since Python 2.7.18 was just release on April 20th, I don't believe completely dropping 2.7 fully would be good yet, as people are still migrating to other versions.  Unfortunately, the current version doesn't do any sort of tracking to the sync server as to what python version is being run or the denyhosts version being used.

So, while I agree that python 2.7 support will need to be removed, I don't believe that it should be removed right now.  I think deprecating python 2.7 support and putting it into it's own branch will be good for EOY to allow users to migrate to python 3.


```py_version = sys.version_info
if py_version[0] == 2:
    # python 2
    from ipaddr import IPAddress
elif py_version[0] == 3:
    # python 3
    from ipaddress import ip_address
```

**Comment by josev814** [comment]
I did add additional operating systems to the Travis-CI build yesterday to test against Xenial and Bionic.  I haven't seen the option within Travis-CI to add Focal.  Once they get Focal added, I can run the unit tests against Focal to ensure 20 LTS is supported properly.

**Comment by AdasOsorus** [comment]
@josev814  Thank you for this follow-up. If I can do something, let me know.

**Comment by AdasOsorus** [comment]
I just find something to add to be "compliant" to 20.04LTS ... the iptables location isn't the one pointed by the daemon (/sbin/iptables)
I add this to let denyhosts to add iptables rules:
`ln -s /usr/sbin/iptables /sbin/iptables
`
Now the rules are added automatically...

**Comment by josev814** [comment]
Within the conf file there's a setting to set the iptables location. ```IPTABLES = /sbin/iptables```.  We don't automatically detect the location of iptables.  It's part of the config setup for users to do for their OS.  We might be able to change that down the road.

**Comment by AdasOsorus** [comment]
My bad... *note to myself* --> RTFM
