### ISSUE TITLE
Sync fail [can't find the reason]

### ISSUE THREAD

**Issue by AdasOsorus** [denyhosts/denyhosts#119]
denyhost on Ubuntu on 20.04-LTS on Python 3.8

run command:
python /usr/local/bin/denyhosts.py --config /etc/denyhosts.conf --daemon

Log:
`cat /var/log/denyhosts
`
2020-04-28 23:41:12,732 - denyhosts   : INFO     DenyHosts launched with the following args:
2020-04-28 23:41:12,732 - denyhosts   : INFO        /usr/local/bin/denyhosts.py --config /etc/denyhosts.conf --daemon
2020-04-28 23:41:12,733 - prefs       : INFO     DenyHosts configuration settings:
2020-04-28 23:41:12,733 - prefs       : INFO        ADMIN_EMAIL: [root@localhost]
2020-04-28 23:41:12,733 - prefs       : INFO        AGE_RESET_INVALID: [864000]
2020-04-28 23:41:12,733 - prefs       : INFO        AGE_RESET_RESTRICTED: [2160000]
2020-04-28 23:41:12,733 - prefs       : INFO        AGE_RESET_ROOT: [2160000]
2020-04-28 23:41:12,733 - prefs       : INFO        AGE_RESET_VALID: [432000]
2020-04-28 23:41:12,733 - prefs       : INFO        ALLOWED_HOSTS_HOSTNAME_LOOKUP: [NO]
2020-04-28 23:41:12,733 - prefs       : INFO        BLOCKPORT: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        BLOCK_SERVICE: [sshd]
2020-04-28 23:41:12,733 - prefs       : INFO        DAEMON_LOG: [/var/log/denyhosts]
2020-04-28 23:41:12,733 - prefs       : INFO        DAEMON_LOG_MESSAGE_FORMAT: [%(asctime)s - %(name)-12s: %(levelname)-8s %(message)s]
2020-04-28 23:41:12,733 - prefs       : INFO        DAEMON_LOG_TIME_FORMAT: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        DAEMON_PURGE: [3600]
2020-04-28 23:41:12,733 - prefs       : INFO        DAEMON_SLEEP: [90]
2020-04-28 23:41:12,733 - prefs       : INFO        DENY_THRESHOLD_INVALID: [3]
2020-04-28 23:41:12,733 - prefs       : INFO        DENY_THRESHOLD_RESTRICTED: [1]
2020-04-28 23:41:12,733 - prefs       : INFO        DENY_THRESHOLD_ROOT: [3]
2020-04-28 23:41:12,733 - prefs       : INFO        DENY_THRESHOLD_VALID: [5]
2020-04-28 23:41:12,733 - prefs       : INFO        DETECT_DOVECOT_LOGIN_ATTEMPTS: [no]
2020-04-28 23:41:12,733 - prefs       : INFO        ETC_DIR: [/etc]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_DOVECOT_ENTRY_REGEX: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_ENTRY_REGEX: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_ENTRY_REGEX2: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_ENTRY_REGEX3: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_ENTRY_REGEX4: [None]
2020-04-28 23:41:12,733 - prefs       : INFO        FAILED_ENTRY_REGEX5: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        FAILED_ENTRY_REGEX6: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        FAILED_ENTRY_REGEX7: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        FAILED_ENTRY_REGEX8: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        FAILED_ENTRY_REGEX9: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        HOSTNAME_LOOKUP: [NO]
2020-04-28 23:41:12,734 - prefs       : INFO        HOSTS_DENY: [/etc/hosts.deny]
2020-04-28 23:41:12,734 - prefs       : INFO        IPTABLES: [/sbin/iptables]
2020-04-28 23:41:12,734 - prefs       : INFO        LOCK_FILE: [/var/run/denyhosts.pid]
2020-04-28 23:41:12,734 - prefs       : INFO        PFCTL_PATH: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        PF_TABLE: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        PF_TABLE_FILE: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        PLUGIN_DENY: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        PLUGIN_PURGE: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        PURGE_DENY: [2419200]
2020-04-28 23:41:12,734 - prefs       : INFO        PURGE_THRESHOLD: [0]
2020-04-28 23:41:12,734 - prefs       : INFO        RESET_ON_SUCCESS: [yes]
2020-04-28 23:41:12,734 - prefs       : INFO        SECURE_LOG: [/var/log/auth.log]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_DATE_FORMAT: [%a, %d %b %Y %H:%M:%S %z]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_FROM: [DenyHosts <nobody@localhost>]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_HOST: [localhost]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_PASSWORD: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_PORT: [25]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_SUBJECT: [DenyHosts Report]
2020-04-28 23:41:12,734 - prefs       : INFO        SMTP_USERNAME: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        SSHD_FORMAT_REGEX: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        SUCCESSFUL_ENTRY_REGEX: [None]
2020-04-28 23:41:12,734 - prefs       : INFO        SUSPICIOUS_LOGIN_REPORT_ALLOWED_HOSTS: [YES]
2020-04-28 23:41:12,734 - prefs       : INFO        SYNC_DOWNLOAD: [yes]
2020-04-28 23:41:12,734 - prefs       : INFO        SYNC_DOWNLOAD_RESILIENCY: [18000]
2020-04-28 23:41:12,735 - prefs       : INFO        SYNC_DOWNLOAD_THRESHOLD: [3]
2020-04-28 23:41:12,735 - prefs       : INFO        SYNC_INTERVAL: [3600]
2020-04-28 23:41:12,735 - prefs       : INFO        SYNC_SERVER: [http://xmlrpc.denyhosts.net:9911]
2020-04-28 23:41:12,735 - prefs       : INFO        SYNC_UPLOAD: [yes]
2020-04-28 23:41:12,735 - prefs       : INFO        SYSLOG_REPORT: [no]
2020-04-28 23:41:12,735 - prefs       : INFO        WORK_DIR: [/var/lib/denyhosts]
2020-04-28 23:41:12,735 - denyhosts   : INFO     restricted: set()
2020-04-28 23:41:12,735 - denyhosts   : INFO     launching DenyHosts daemon (version 3.0)...
2020-04-28 23:41:12,737 - denyhosts   : INFO     DenyHost daemon is now running, pid: 17935
2020-04-28 23:41:12,737 - denyhosts   : INFO     send daemon process a TERM signal to terminate cleanly
2020-04-28 23:41:12,737 - denyhosts   : INFO       eg.  kill -TERM 17935
2020-04-28 23:41:12,737 - denyhosts   : INFO     monitoring log: /var/log/auth.log
2020-04-28 23:41:12,737 - denyhosts   : INFO     sync_time: 3600
2020-04-28 23:41:12,737 - denyhosts   : INFO     daemon_purge:      3600
2020-04-28 23:41:12,737 - denyhosts   : INFO     daemon_sleep:      90
2020-04-28 23:41:12,737 - denyhosts   : INFO     purge_sleep_ratio: 40
2020-04-28 23:41:12,737 - denyhosts   : INFO     sync_time:      : 3600
2020-04-28 23:41:12,737 - denyhosts   : INFO     sync_sleep_ratio: 40
2020-04-29 00:41:15,218 - denyfileutil: INFO     purging entries older than: Wed Apr  1 00:41:15 2020
2020-04-29 00:41:15,220 - denyfileutil: INFO     num entries purged: 0
2020-04-29 00:41:15,222 - sync        : ERROR    invalid literal for int() with base 10: ''
2020-04-29 00:43:25,738 - sync        : ERROR    [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/DenyHosts/sync.py", line 116, in receive_new_hosts
    data = self.__server.get_new_hosts(timestamp,
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
2020-04-29 01:43:28,242 - denyfileutil: INFO     purging entries older than: Wed Apr  1 01:43:28 2020
2020-04-29 01:43:28,243 - denyfileutil: INFO     num entries purged: 0
2020-04-29 01:43:28,244 - sync        : ERROR    invalid literal for int() with base 10: ''
2020-04-29 01:45:39,242 - sync        : ERROR    [Errno 110] Connection timed out

**Comment by josev814** [comment]
The sync server is wrong

It should be pointing to sync.denyhosts.org:9911 or deny.resonatingmedia.com:9911 (both are the same server)

Your setup has xmlrpc.denyhosts.net:9911 which is an old config.  Where did you get your denyhosts setup from, just curious as to where it came from so I can look into getting that updated.

Please close the issue if this resolves your issue @AdasOsorus

**Comment by AdasOsorus** [comment]
@josev814 The config file was the same for a very long time which was running on my server... I change sync address to one you proposed... and update my *.conf too  !

Here is my log after sync... seems to work, but one "Error"
(...)
```
2020-04-30 18:54:31,788 - denyhosts   : INFO     sync_sleep_ratio: 30
**2020-04-30 19:09:32,555 - sync        : ERROR    invalid literal for int() with base 10: ''**
2020-04-30 19:09:33,469 - sync        : INFO     received 50 new hosts
2020-04-30 19:09:33,470 - denyhosts   : INFO     received new hosts: ['61.161.143.170', '159.203.10.216', '95.217.58.48', '188.131.234.51', '104.248.253.5', '51.83.135.1', '132.145.165.87', '37.97.221.77', '124.219.109.45', '183.238.0.242', '51.77.146.156', '68.183.193.185', '80.15.71.48', '217.168.131.26', '152.136.204.232', '46.41.150.247', '111.231.60.213', '54.68.7.236', '177.52.255.67', '37.49.226.212', '37.49.226.211', '178.128.221.85', '62.171.150.133', '118.25.123.165', '179.107.7.220', '51.158.124.238', '195.66.163.11', '182.61.49.108', '103.9.195.59', '62.234.148.144', '177.99.210.179', '197.234.193.46', '213.226.114.41', '54.38.175.224', '73.63.60.242', '195.28.70.220', '2.139.220.30', '200.54.113.58', '13.66.16.96', '62.171.149.22', '187.34.249.245', '201.148.87.82', '190.54.4.98', '35.226.79.112', '165.227.135.34', '103.236.253.86', '107.170.135.29', '125.45.12.133', '209.141.37.175', '91.121.173.98']
2020-04-30 19:09:33,471 - denyhosts   : INFO     Creating new firewall rule /sbin/iptables -I INPUT -s 61.161.143.170 -j DROP
```

**Comment by josev814** [comment]
Pretty sure the error you are seeing is from line 54 in sync.py.  Since you weren't able to sync previously, the sync time would have been set to '' and trying to get int() from '' would have errored.  That error is caught on line 58, and then line 59 returns 0 for the last sync time.  So, that error is nothing to worry about.  I will look at patching that to be cleaner though.

**Comment by AdasOsorus** [comment]
Great! ... meanwhile, I delete the file and restart the daemon and it works.

**Comment by josev814** [comment]
I already have the code set to fix the issue.  It's just running against Travis-CI, before I merge it in
