### ISSUE TITLE
Purge Hosts Error

### ISSUE THREAD

**Issue by bigwavedave42** [denyhosts/denyhosts#171]
On yesterday's master, I got the following today:

2020-05-23 14:14:13,701 - denyfileutil: INFO     num entries purged: 105
2020-05-23 14:14:13,701 - root        : ERROR    __init__() should return None, not 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/DenyHosts/deny_hosts.py", line 242, in sleepandpurge
    purged_hosts = Purge(self.__prefs, purge_time)
TypeError: __init__() should return None, not 'list'

Seems to have crashed the daemon as a result.  I had quite a few successful purges prior to it, so not sure what was special about this one.

**Comment by bigwavedave42** [comment]
Hmmm... just saw it again.  

2020-05-23 20:32:10,761 - denyfileutil: INFO     num entries purged: 91
2020-05-23 20:32:10,761 - root        : ERROR    __init__() should return None, not 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/DenyHosts/deny_hosts.py", line 242, in sleepandpurge
    purged_hosts = Purge(self.__prefs, purge_time)
TypeError: __init__() should return None, not 'list'

Just confirmed on latest master.

**Comment by josev814** [comment]
This should be resolved. It was an issue I introduced with capturing the ips that were removed so iptables could handle removing the ips as well.

Can you validate that the issue no longer occurs with the latest merge?

**Comment by bigwavedave42** [comment]
It just survived one purge event, so it seems better! Thank you!

I'll continue monitoring it

**Comment by bigwavedave42** [comment]
I feel pretty confident at this point, that this is resolved, so I'll close it.
