### ISSUE TITLE
Sync fails with "'NoneType' object has no attribute 'rfind'"

### ISSUE THREAD

**Issue by Papafox** [denyhosts/denyhosts#19]
Following a new install of DenyHosts v2.9 on a new linux image, sync consistantly fails.  The following error occurs on sync:

    2015-01-30 02:54:52,481 - denyfileutil: INFO     purging entries older than: Sun Jan 25 02:54:52 2015
    2015-01-30 02:54:52,484 - denyfileutil: INFO     num entries purged: 0
    2015-01-30 02:54:52,485 - sync        : ERROR    'NoneType' object has no attribute 'rfind'
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/DenyHosts/sync.py", line 135, in receive_new_hosts
        self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
      File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
        verbose=self.__verbose
      File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1284, in single_request
        h = self.make_connection(host)
      File "/usr/local/lib/python2.7/dist-packages/DenyHosts/sync.py", line 22, in make_connection
        h = HTTP(self.proxy)
      File "/usr/lib/python2.7/httplib.py", line 1079, in __init__
        self._setup(self._connection_class(host, port, strict))
      File "/usr/lib/python2.7/httplib.py", line 704, in __init__
        self._set_hostport(host, port)
      File "/usr/lib/python2.7/httplib.py", line 723, in _set_hostport
        i = host.rfind(':')
    AttributeError: 'NoneType' object has no attribute 'rfind'

Previous to this I had an extra error:

    2015-01-30 00:54:44,944 - sync        : ERROR    [Errno 2] No such file or directory: '/var/lib/denyhosts/sync-timestamp'

I created a file of the correct name and copied the contents from a system running v2.6

**Comment by Papafox** [comment]
I had set '`SYNC_PROXY_SERVER = `'.  Removing the statement resolved the error `AttributeError: 'NoneType' object has no attribute 'rfind'`, but now I get:

    2015-01-31 03:38:56,635 - sync        : ERROR    'SYNC_PROXY_SERVER'
    2015-01-31 03:38:56,635 - sync        : ERROR    Could not initiate xmlrpc connection

I am not using a proxy.  What value should `SYNC_PROXY_SERVER` have?
