### ISSUE TITLE
deny.resonatingmedia.com public sync server down

### ISSUE THREAD

**Issue by acjohnson** [denyhosts/denyhosts#196]
Is there are new sync server users can switch to? I'm getting this error on multiple machines and can't connect to 13.75.152.41 on  port `9911`:
```
2020-09-08 20:02:32,903 - sync        : ERROR    [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DenyHosts/sync.py", line 238, in __receive_new_hosts
    sync_dl_resiliency
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Connection timed out
```

Thanks!

**Comment by T0mScott** [comment]
Yes, there is a new server name since some years that works: http://sync.denyhosts.org:9911

**Comment by acjohnson** [comment]
Awesome thank you @josev814 ! #198
