### ISSUE TITLE
.deb file did not install /usr/share/denyhosts

### ISSUE THREAD

**Issue by jamesderlin** [denyhosts/denyhosts#202]
I downloaded `denyhosts_3.1.2-2_all.deb` from https://sourceforge.net/projects/denyhosts/files/denyhosts/3.1.2-beta/ and installed it with `sudo apt install ./denyhosts_3.1.2-2_all.deb`, but it did not create `/usr/share/denyhosts`.

On my Debian 10.9 system, running `/usr/local/bin/denyhosts.py` then fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 14, in <module>
    from DenyHosts.util import die, setup_logging, is_true
  File "/usr/share/denyhosts/DenyHosts/util.py", line 12, in <module>
    from ipaddr import IPAddress
ImportError: No module named ipaddr
```
and running `denyhosts.py` explicitly with `python3` results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 8, in <module>
    import DenyHosts.python_version
ModuleNotFoundError: No module named 'DenyHosts'
```
when it tries and fails to find `DenyHosts/denyhosts.py` from `/usr/share/denyhosts`.

A workaround is to do:

```bash
mkdir /usr/share/denyhosts
ln -s /usr/local/lib/python2.7/dist-packages/DenyHosts /usr/share/denyhosts
```

**Comment by sistemascta** [comment]
Can confirm this works in Debian 12. Thanks!
