### ISSUE TITLE
Does not install from git repository correctly.

### ISSUE THREAD

**Issue by cnobile2012** [denyhosts/denyhosts#206]
I found many issues when installing from the git repo.

1. Python path to DenyHost incorrect.
2. The `requests` package is not in the setup.py file (requires=["ipaddr"] should also have `requests`).
3. SyntaxError: Non-ASCII character '\xd1' in file /usr/local/lib/python3.8/dist-packages/charset_normalizer/__init__.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (I fixed this by adding # -*- coding: utf-8 -*-)
4. Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 18, in <module>
    from DenyHosts.deny_hosts import DenyHosts
  File "/usr/local/lib/python3.8/dist-packages/DenyHosts/deny_hosts.py", line 24, in <module>
    from .sync import Sync
  File "/usr/local/lib/python3.8/dist-packages/DenyHosts/sync.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.8/dist-packages/requests/__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "/usr/local/lib/python3.8/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/usr/local/lib/python3.8/dist-packages/charset_normalizer/api.py", line 28
    sequences: bytes,
             ^
SyntaxError: invalid syntax

At this point, I stopped trying to fix the issues.
Could the last two problems be a too recent `charset_normalizer` package?

**Comment by qs5779** [comment]
I haven't submitted a PR yet, but I did make local changes to the setup to add requests for python >= 3. I also believe it requies ipaddress as opposed to ipaddr on python 3. Are you using a standard distribution python 3.8? If yes, share the platform and os name and codename if it is a Debian derivative and maybe I can ttest my updates against the same version. I create personal packages for three Debian dists ( buster, focal, impish ), I seem to recall either buster or focal stock images use python 3.8 and I had no issues using the setup.py from this dist though.

**Comment by cnobile2012** [comment]
I posted this almost 6 months ago, I almost forgot about it.

This is a standard Ubuntu install, I did not compile it myself.

```
$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```

```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I hope this is what you were looking for.
