### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by dtd41** [denyhosts/denyhosts#207]
starting got the following error:
denyhosts.py -c /usr/local/etc/denyhosts.conf --foreground 
Unable to create file specified by HOSTS_DENY variable.
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 155, in <module>
    setup_logging(prefs, enable_debug, verbose, daemon)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/util.py", line 28, in setup_logging
    fh = logging.handlers.RotatingFileHandler(daemon_log, 'a', 1024*1024, 7)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/denyhosts'

This is corrected by adding --ignore. The error is, I think, the open in handlers.py should be in a try/except block. It took me a while to check out things until I got to the problem.

source is denyhosts-py37-3.1.2 on FreeBSD 12.2

**Comment by qs5779** [comment]
I am not sure about bsd but on linux the product should be run as root as by default writing to /etc/hosts.deny and /var/log/denyhosts would require root permissions.
