### ISSUE TITLE
ipaddr module dependency

### ISSUE THREAD

**Issue by lukaswu-orig** [denyhosts/denyhosts#233]
### Description

Hello,

I'm having hard times on my Slackware current while trying to install DenyHosts, whatever I do it ends up with:
ImportError: No module named ipaddr

AFAIK 'ipaddr' module is replaced by 'ipaddress', I tried backported modules but none of them worked for me.

Could you recommend which module should be used?

### DenyHosts Version

3.1

### Reproduction steps

```bash
1. python setup.py install
2. Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from DenyHosts.util import normalize_whitespace
  File "/usr/src/denyhosts/DenyHosts/util.py", line 14, in <module>
    from ipaddr import IPAddress
ImportError: No module named ipaddr
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Slackware64-current

**Comment by josev814** [comment]
What version of Python are you using?  According to the DenyHosts Utils file it's attempting to import ipadrr, because you are using Python 2.x.  If that's the case, you do need ipaddr installed from pypi.  I did check and it appears that it should be possible to get rid of the Python check and just use ipaddress, since it was backported on pypi.

**Comment by lukaswu-orig** [comment]
Hi Jose,
python version is 2.7.18. Basically you described the problem I came with :), for ipaddr pypi reads:
'It has been superseded by ipaddress from the Python 3 standard library, and its Python 2 backport.'
Now the backport module I found to be kind of wide use is deleted (py2-ipaddress), thus asking which backport module you recommend to use.
'it appears that it should be possible to get rid of the Python check and just use ipaddress, since it was backported on pypi.'
Do you mean it is not needed and we could expect a newer version of DenyHosts soon or I should try any workaround?

Luk

**Comment by josev814** [comment]
I know we've been working on moving from Python2 to Python3, since Python2 has been EOL since 2020.  Is it possible for you to move to Python3?  If not, I can look at our branches and update an older branch to apply the fix for you.

**Comment by josev814** [comment]
@lukaswu-orig I was looking I have a branch cut with a PR for Python 2.6 and 2.7 changes applied.  The issue I'm running into though is that GitHub Actions no longer support Python 2.x versions.  It might take me a bit longer to get the changes applied since I'll have to look at another method to be able to ensure that our unit tests run for Python 2.x.

**Comment by josev814** [comment]
With Python3.9.18, you can either use the same release that you have downloaded or clone the repository.  We haven't cut a release in a while even though we have a ton of updates regarding Python3.x now.  I probably won't be able to cut a good final release of 3.1 or 3.2 on this until the summer.  Just with everything else that I have going on.

**Comment by ammgws** [comment]
@josev814 Just wondering, does your schedule still look OK for this summer?

**Comment by josev814** [comment]
@ammgws My schedule cleared up a bit.  Just taking a week vacation before getting back to the grind.  I'll be able to set some time aside to work on this over the summer.

**Comment by Akindotcome** [comment]
@josev814 
Were you able to close this issue as planned?

**Comment by lukaswu-orig** [comment]
> [@josev814](https://github.com/josev814) Were you able to close this issue as planned?

TBH I do not remember as the server was reinstalled at certain point and since then I'm not using this script.

**Comment by Akindotcome** [comment]
@lukaswu-orig 
That's nice
