### ISSUE TITLE
KeyError: 'FAILED_ENTRY_REGEX10'

### ISSUE THREAD

**Issue by panzhengyu** [denyhosts/denyhosts#66]
[root@panzhengyu denyhosts]#  python /usr/local/bin/denyhosts.py --daemon --config=/etc/denyhosts.conf
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 229, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/local/lib/python2.7/site-packages/DenyHosts/deny_hosts.py", line 56, in **init**
    self.init_regex()
  File "/usr/local/lib/python2.7/site-packages/DenyHosts/deny_hosts.py", line 576, in init_regex
    FAILED_ENTRY_REGEX_MAP[i])
  File "/usr/local/lib/python2.7/site-packages/DenyHosts/deny_hosts.py", line 558, in get_regex
    val = self.__prefs.get(name)
  File "/usr/local/lib/python2.7/site-packages/DenyHosts/prefs.py", line 216, in get
    return self.__data[name]
KeyError: 'FAILED_ENTRY_REGEX10'

**Comment by Papafox** [comment]
The current build is broken.  Reset to the previous commit:

Display the history to obtain the hash of the previous commit
git --no-pager reflog








————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by panzhengyu** [comment]
It‘s right,Thank you’

**Comment by josev814** [comment]
The reason for this issue was because of the entry not being in prefs.py.  I updated it in my repo and requested a merge, so this should be resolved soon.

**Comment by josev814** [comment]
This bug looks to have been resolved when looking at the regex.py comparisons in the history.  REGEX10 was moved to replace REGEX9 to handle ssh key auth
