### ISSUE TITLE
offset file exception handling

### ISSUE THREAD

**Issue by AndCycle** [denyhosts/denyhosts#96]
just simple report back about this missing handle for `ValueError` exception,
when DenyHosts access `/var/lib/denyhosts/offset` which is empty.

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/denyhosts.py", line 229, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/lib64/python2.7/site-packages/DenyHosts/deny_hosts.py", line 69, in __init__
    last_offset = self.file_tracker.get_offset()
  File "/usr/lib64/python2.7/site-packages/DenyHosts/filetracker.py", line 60, in get_offset
    last_line, last_offset = self.__get_last_offset()
  File "/usr/lib64/python2.7/site-packages/DenyHosts/filetracker.py", line 22, in __get_last_offset
    offset = int(fp.readline())
ValueError: invalid literal for int() with base 10: ''
```

**Comment by larham** [comment]
Thanks for the post, @AndCycle , which I found when I too hit this problem. Thanks to your analysis, one workaround appears to be:

`sudo rm /var/lib/denyhosts/offset`

**Comment by josev814** [comment]
@larham and @AndCycle I've merged in an update that should resolve your issue.  I also have a unit test written out the should test for this bug in the future.

**Comment by josev814** [comment]
@larham @AndCycle Can either of you validate that the bug is fixed for you now?  I'd like to close this bug.

**Comment by larham** [comment]
Thanks for the fix and test, @josev814 works for me
