### ISSUE TITLE
Is denyhosts still alive?

### ISSUE THREAD

**Issue by syeo66** [denyhosts/denyhosts#98]
Lates commit: 20 Nov 2017
Open PRs back to 23 Sep 2015
Absolutely no action on Issues since 22 Jul 2017

Looks unmaintained to me.

**Comment by adriel** [comment]
Yeah, it doesn't look good. :( 
Though it appears people are still using it, judging by the stats on http://sync.denyhosts.org:9911/
It appears around 80 clients are still submitting IPs.

*Disclaimer, I manage the server behind sync.denyhosts.org

**Comment by fgc92** [comment]
It has been WEEKS of Connection Timed Out for me on all of my servers to DenyHosts. 
Should we run a new server somewhere?

**Comment by josev814** [comment]
When I access the sync.denyhosts.org site via http, that seems to be working correctly. I'll check to see if I can access the site on one of my dev boxes to see if there's an issue with the client itself connecting since the last push I made.

**Comment by adriel** [comment]
Had a look on the server end and it seems to be running fine. (There was some `InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.` errors, but I've just fixed that now, but it shouldn't cause timeouts). My denyhosts client also seems to work receiving IPs fine, not sure about submitting new IPs. 

What's your SYNC_SERVER config set to?
Mine is: `SYNC_SERVER = http://sync.denyhosts.org:9911`

**Comment by fgc92** [comment]
I use http://xmlrpc.denyhosts.net:9911
But note that the version I used is actually from the original website. I see that the one on github has a higher version. Don't they all use the same server?

**Comment by josev814** [comment]
@fgc92 Can you check what you have in your denyhosts.conf file for the SYNC_SERVER and your sync settings?  When I check the connection it works fine. I've included some python code that you can use to test your connection.


```
import logging
import os
import time
import sys

if sys.version_info < (3, 0):
        from xmlrpclib import ServerProxy
else:
        from xmlrpc.client import ServerProxy

try:
        server = ServerProxy('http://sync.denyhosts.org:9911')
        print("Connected to server: " + str(server))
        server = ServerProxy('http://deny.resonatingmedia.com:9111')
        print("Connected to server: " + str(server))
except Exception as e:
        print(e)
```

**Comment by josev814** [comment]
Unfortunately, the server isn't standardized.  I haven't seen a way to update the pypi version even though I've contacted the listed owner about it.  For the moment the best way to have the most up to date version is to use the GitHub version.  From what I've noticed on updates, denyhosts.conf gets wiped out.  I believe one of my recent updates actually backs up the conf file, but I'm not sure that I've pushed that out yet.

**Comment by josev814** [comment]
I can look into adding multiple servers in the config down the road, so if one server fails to connect it can go to an alternate server.  I someone would like that please submit it as an issue and I can look at working on that.

**Comment by adriel** [comment]
Also http://xmlrpc.denyhosts.net:9911 is the old project's sync server, it's not active anymore.

Also @josev814 I didn't know there were other servers active? Both http://sync.denyhosts.org:9911/ and http://deny.resonatingmedia.com:9911/ point to the same server (the one I maintain).

**Comment by josev814** [comment]
@adriel I wasn't aware they were the same server.

**Comment by josev814** [comment]
@adriel Thoughts on changing to use JSON for the sync server rather than XMLRPC?  I've been thinking of changing it to JSON.

**Comment by fgc92** [comment]
Is the original server still working, and original owner still in the loop? 
Or is this project a totally new fork from the original denyHosts? 
I can definitely help with the servers and updating the clients.

**Comment by fgc92** [comment]
Also, can the server http://sync.denyhosts.org:9911 work with version 2.6?
Or do I need to update all my servers to the version available on github?

**Comment by adriel** [comment]
@josev814 I'm all for JSON, never was a big fan of XMLRPC.

**Comment by josev814** [comment]
The original server is offline, and they seem to have abandoned to project.  The project is a continuation of the original project, but being updated periodically.
2.6 should still work with the new sync server.

**Comment by fgc92** [comment]
I have setup SYNC_SERVER = http://sync.denyhosts.org:9911 on a 2.6 version. I will monitor and if it works will change all my servers. 

On the other hand, I agree with JSON and can help on a new major version.

**Comment by fgc92** [comment]
The same issue still happens (but now it's Error: Connection refused) with V2.6

**Comment by josev814** [comment]
Not sure why you're getting connection refused.  I've been sending new hosts to the box tonight. Times are EST.
```# cat /var/log/denyhosts | grep sent
2019-08-31 21:52:47,014 - sync        : INFO     sent 1 new host
2019-08-31 23:14:34,391 - sync        : INFO     sent 1 new host
2019-08-31 23:55:28,651 - sync        : INFO     sent 1 new host
```

**Comment by fgc92** [comment]
2019-09-01 07:00:05,323 - denyfileutil: INFO     purging entries older than: Sat Sep  1 07:00:05 2018
2019-09-01 07:00:05,342 - denyfileutil: INFO     num entries purged: 0
2019-09-01 07:00:06,594 - sync        : ERROR    [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DenyHosts/sync.py", line 117, in receive_new_hosts
    self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by fgc92** [comment]
I will install the latest version from github and see how it goes.

**Comment by fgc92** [comment]
Same issue with version 3.0

2019-09-03 09:43:01,499 - denyhosts   : INFO     DenyHost daemon is now running, pid: 2759
2019-09-03 09:43:01,500 - denyhosts   : INFO     send daemon process a TERM signal to terminate cleanly
2019-09-03 09:43:01,500 - denyhosts   : INFO       eg.  kill -TERM 2759
2019-09-03 09:43:01,500 - denyhosts   : INFO     monitoring log: /var/log/secure
2019-09-03 09:43:01,500 - denyhosts   : INFO     sync_time: 3600
2019-09-03 09:43:01,500 - denyhosts   : INFO     daemon_purge:      3600
2019-09-03 09:43:01,500 - denyhosts   : INFO     daemon_sleep:      30
2019-09-03 09:43:01,500 - denyhosts   : INFO     purge_sleep_ratio: 120
2019-09-03 09:43:01,500 - denyhosts   : INFO     sync_time:      : 3600
2019-09-03 09:43:01,501 - denyhosts   : INFO     sync_sleep_ratio: 120





2019-09-03 10:43:04,051 - denyfileutil: INFO     purging entries older than: Mon Sep  3 10:43:04 2018
2019-09-03 10:43:04,068 - denyfileutil: INFO     num entries purged: 0
2019-09-03 10:43:04,069 - sync        : ERROR    [Errno 2] No such file or directory: '/var/lib/denyhosts/sync-timestamp'
2019-09-03 10:43:05,097 - sync        : ERROR    [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DenyHosts/sync.py", line 119, in receive_new_hosts
    self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2019-09-03 11:43:07,375 - denyfileutil: INFO     purging entries older than: Mon Sep  3 11:43:07 2018
2019-09-03 11:43:07,386 - denyfileutil: INFO     num entries purged: 0
2019-09-03 11:43:07,386 - sync        : ERROR    [Errno 2] No such file or directory: '/var/lib/denyhosts/sync-timestamp'
2019-09-03 11:43:08,389 - sync        : ERROR    [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DenyHosts/sync.py", line 119, in receive_new_hosts
    self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by josev814** [comment]
Has something with your network changed?  I'm getting messages with received 0 new hosts when I'm checking.  No errors.
```2019-09-03 11:46:08,538 - sync        : INFO     received 0 new hosts
2019-09-03 11:56:21,450 - sync        : INFO     received 0 new hosts
2019-09-03 12:06:34,346 - sync        : INFO     received 0 new hosts
2019-09-03 12:16:47,302 - sync        : INFO     received 0 new hosts
2019-09-03 12:27:00,264 - sync        : INFO     received 0 new hosts
2019-09-03 12:37:13,673 - sync        : INFO     received 0 new hosts
2019-09-03 12:47:26,678 - sync        : INFO     received 0 new hosts
2019-09-03 12:57:39,576 - sync        : INFO     received 0 new hosts
```

**Comment by fgc92** [comment]
Nothing changed. 
When I try the script you gave above, it works:

root@xanadu:/goinfre/TEMP> python test.py
Connected to server: <ServerProxy for sync.denyhosts.org:9911/RPC2>
Connected to server: <ServerProxy for deny.resonatingmedia.com:9111/RPC2>

**Comment by josev814** [comment]
when you do `ls -l /var/lib/denyhosts/` do you have a sync-timestamp file in there?  If so, what timestamp do you have?  Mine is 1567531085

**Comment by fgc92** [comment]
No, as the error message says, no timestamp file:

2019-09-03 11:43:07,386 - sync : ERROR [Errno 2] No such file or directory: '/var/lib/denyhosts/sync-timestamp'

**Comment by fgc92** [comment]
I manually created the file. Waiting to see what happens now.

**Comment by josev814** [comment]
Are there any other files in that directory?  I'm just curious if there's a permission issue, or it it just didn't create the file by default

**Comment by fgc92** [comment]
Yes, there are files:

total 12
drwxr-xr-x   2 root root 4096 Sep  3 13:30 ./
drwxr-xr-x. 37 root root 4096 Sep  3 09:37 ../
-rw-r--r--   1 root root    0 Sep  3 12:05 hosts
-rw-r--r--   1 root root    0 Sep  3 12:05 hosts-restricted
-rw-r--r--   1 root root    0 Sep  3 12:05 hosts-root
-rw-r--r--   1 root root    0 Sep  3 12:05 hosts-valid
-rw-r--r--   1 root root   96 Sep  3 12:05 offset
-rw-r--r--   1 root root    0 Sep  3 12:05 suspicious-logins
-rw-r--r--   1 root root    0 Sep  3 13:30 sync-timestamp
-rw-r--r--   1 root root    0 Sep  3 12:05 users-hosts
-rw-r--r--   1 root root    0 Sep  3 12:05 users-invalid
-rw-r--r--   1 root root    0 Sep  3 12:05 users-valid


Note that I created the timestamp one manually.
I still have errors.

**Comment by adriel** [comment]
If you have docker installed you could try the docker container I've made, see if that also errors out. https://hub.docker.com/r/adriel/denyhosts

**Comment by bentolor** [comment]
> Though it appears people are still using it, judging by the stats on http://sync.denyhosts.org:9911/
> It appears around 320 clients are still submitting IPs.

By occasion I realized that my installation spilled tons of unable to connect errors. After reading this issue I realized that I'm using the no-longer-working `http://xmlrpc.denyhosts.net:9911` sync server. I assume most of the users are running in this situation because that's their original configuration.

So there might be a much larger user base like me who yet just haven't realized that they need to reconfigure things.

**Comment by josev814** [comment]
@adriel I've been talking to Phil Schwartz.  It seems that he's willing to possibly transfer the .net domain to me or to point the xmlrpc.denyhosts.net domain over to sync.denyhosts.org.  He did say that there will be an influx of bandwidth from the xmlrpc domain.  He used to host it on his home server.  I just wanted to verify that forwarding xmlrpc to sync.denyhosts.org would be okay with you.

**Comment by adriel** [comment]
Yeah, should be fine on my end. Thanks for checking.

**Comment by josev814** [comment]
Thank you.  I let Phil know, so hopefully, he can make the changes soon, and we'll start to see an uptick in the number of banned hosts are being reported.  I did take a look at your denyhosts image yesterday and saw that it had 100K+ downloads.  So, it might be a massive hit that you see.

**Comment by josev814** [comment]
@adriel I have the ability to make repos for the denyhosts organization now.  If I create a repo for denyhosts docker, would you commit your docker build file and create a README for it?

**Comment by adriel** [comment]
Hmm yeah, I would take the 100K+ downloads with a grain of salt. Allot of people use something called [watchtower](https://github.com/containrrr/watchtower) to keep images up to date, basically, it seems each time watchtower checks for an update it triggers a "download", which is why you see a lot of containers have millions of "downloads".
I've found checking how many stars a container has is a better metric of how popular it is.

But yeah I can put the docker files in a denyhosts org repo if you make one. 
Or would it be better to fork the [repo](https://github.com/adriel/denyhosts-docker) the docker image runs off currently, then change the image over to the denyhosts org once it's forked?
Either way works for me.

I'll also see if I can update the docker image to use Python 3, as I just noticed it's still on Python 2. (and maybe update the server image to the latest Debian version)

**Comment by josev814** [comment]
I forked your repo for docker-denyhosts and docker-denyhosts-sync  to the denyhosts org repo and assigned you as one of the maintainers for the repo.

**Comment by josev814** [comment]
@adriel Phil just pointed xmlrpc.denyhosts.net over to sync.denyhosts.org, so you should start to see an influx of traffic starting today on your VM.

**Comment by adriel** [comment]
Aaah yes, I can definitely see the change haha. Most of it is from the database, so I may need to optimize it a bit, will see how things go.
![image](https://user-images.githubusercontent.com/154217/81353695-dd3c0a00-911d-11ea-8061-5299172d53ae.png)

**Comment by josev814** [comment]
@adriel Can you give it another try?  I made you an admin for the Docker repos.  Also, I went through my own account and linked Docker with GitHub.  It did have the denyhosts organization listed, but I didn't have a grant access option like the article you pointed me to.  I think it's because from a member/admin level we allow users to install applications without requiring owner intervention to approve the application.

**Comment by josev814** [comment]
Could we get an updated estimate of approximately how many ips are submitting records now?

**Comment by adriel** [comment]
Currently, there are 2793. You can check the stats page: http://sync.denyhosts.org:9911/
You may need to clear your cache to see the latest info.

And thanks, the denyhost org now shows up on Docker hub.

![image](https://user-images.githubusercontent.com/154217/81411423-74dd3f00-9196-11ea-8287-298e8791c0ba.png)

**Comment by josev814** [comment]
I completely missed the Number of clients contributing data.  Thanks for the update.

**Comment by josev814** [comment]
@adriel Is the DenyHosts organization on GitHub under your control?  I went to create the organization, and it says it already exists.  When going to hub.docker.com/denyhosts I get a 404 page that it doesn't exist.  I wasn't sure if it's something you're working on, or if I should open up a ticket with them about it.

**Comment by adriel** [comment]
Yeah not sure what's going on with the denyhosts org on docker. I to tried to make one and had the same issue. I only managed to get the denyhost user. (you can the user account if you'd like).

**Comment by josev814** [comment]
I opened up a ticket with docker, so that hopefully we can gain control of the org.  I also asked for contact information of the person that owns the org, so we can request ownership from them if they can't release the org to us.
